# -*- coding: utf-8 -*-
""""лаба3(лавицкий)"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TqhrIUlIdGGwYjFBSUunrc30TUY4hC6L
"""

n=int(input())
if n==1:print('январь')
if n==2:print('февраль')
if n==3:print('март')
if n==4:print('апрель')
if n==5:print('май')
if n==6:print('июнь')
if n==7:print('июль')
if n==8:print('авгусь')
if n==9:print('сентябрь')
if n==10:print('октябрь')
if n==11:print('ноябрь')
if n==12:print('декабрь')

n=int(input())
if n%2==0:
  print('чет')
else:
  print('нечет')

n=int(input())
if n>40:
  print('stonks')
elif n==40:
  print('(ó﹏ò｡)')
else:
  print('notstonks')

n=int(input())
if n%4==0:print('весокосный')
else:print("невесокосный")

n=int(input())
if n==5 or n==2 or n==3:
  print('простое')
elif n%2==0 or n%3==0 or n%5==0 or n%10==0:print('непростое')
else:print('простое')

n=  float(input())
j=  float(input())
a=-246
b=-100
c=n/j
if c==3.6 or (j>a and j<b):
  n,j=j,n
  print(n,j)
else:
  print(n,j)

numbers=[]
for i in range(5):
  num = int(input("Введите число: "))
  numbers.append(num)


uniq = len(numbers) == len(set(numbers))
chet = sum(1 for num in numbers if num % 2 == 0)
minus = sum(1 for num in numbers if num < 0)
prom = sum(1 for num in numbers if -256 <= num <= 1024)

print(" уникальны:", uniq)
print("четные:", chet)
print("отрицательные:", minus)
print("диапозон:", prom)

a=int(input())
b=int(input())
c=int(input())
n=((a**2+b**3)/(c+3))/4
print(n)
print(n)
if n%2==0:
  print('четное')
else:
  print('нечет')